import Link from "next/link";
import { ArrowLeft, CalendarRange, Layers3, Trophy } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import PublicHeader from "@/components/public-header";
import { getHomepageData } from "@/lib/data";

export default async function LeaguesPage() {
  const supabase = await createClient();
  const { data: seasons } = supabase ? await supabase.from("seasons").select("id,name,status,is_current").order("name", { ascending: false }) : { data: [] };
  const { data: groups } = supabase ? await supabase.from("groups").select("id,name,season_id").order("name") : { data: [] };
  const current = seasons?.find((season) => season.is_current) ?? seasons?.[0];
  const currentGroups = (groups ?? []).filter((group) => group.season_id === current?.id);
  const { standings } = await getHomepageData();
  return <main className="public-theme min-h-screen bg-ink"><PublicHeader /><header className="border-b border-white/10 px-5 py-10"><div className="mx-auto max-w-7xl"><Link href="/" className="text-xs font-black uppercase tracking-[0.25em] text-electric"><ArrowLeft size={14} className="mr-2 inline" />AKFL home</Link><h1 className="page-heading mt-4 font-display text-4xl font-black text-white sm:text-5xl">Leagues & seasons</h1><p className="mt-2 text-white/50">Follow every group, phase and competition format.</p></div></header><div className="mx-auto max-w-7xl px-5 py-10"><div className="mb-10 grid gap-4 md:grid-cols-3"><Metric icon={<Trophy />} label="Current season" value={current?.name ?? "No season"} /><Metric icon={<Layers3 />} label="Groups / phases" value={String(currentGroups.length)} /><Metric icon={<CalendarRange />} label="Seasons" value={String(seasons?.length ?? 0)} /></div>{!seasons?.length ? <p className="rounded-2xl border border-dashed border-white/15 p-10 text-center text-white/50">No seasons have been published yet.</p> : <><div className="mb-8 grid gap-4 md:grid-cols-3">{currentGroups.length ? currentGroups.map((group) => <article key={group.id} className="rounded-3xl border border-white/10 bg-panel p-6"><span className="rounded-full bg-electric px-3 py-1 text-[10px] font-black uppercase tracking-widest text-ink">{current?.status ?? "draft"}</span><h2 className="mt-8 font-display text-2xl font-black text-white">{group.name}</h2><p className="mt-2 text-sm text-white/45">{current?.name}</p><Link href="/matches" className="mt-8 inline-flex text-xs font-black uppercase tracking-widest text-electric">View fixtures →</Link></article>) : <article className="rounded-3xl border border-white/10 bg-panel p-6"><h2 className="font-display text-2xl font-black text-white">{current?.name}</h2><p className="mt-2 text-sm text-white/45">League phase fixtures and standings.</p><Link href="/matches" className="mt-8 inline-flex text-xs font-black uppercase tracking-widest text-electric">View fixtures →</Link></article>}</div><StandingsTable standings={standings} /></>}</div></main>;
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-panel p-5"><div className="mb-5 text-electric">{icon}</div><p className="text-xs font-black uppercase tracking-widest text-white/40">{label}</p><p className="mt-2 font-display text-3xl font-black text-white">{value}</p></div>; }

function StandingsTable({ standings }: { standings: Array<{ team_id: string; team_name: string; short_code: string; p: number; w: number; d: number; l: number; gd: number; pts: number }> }) {
  return <section className="overflow-hidden rounded-3xl border border-white/10 bg-panel"><div className="border-b border-white/10 p-6"><p className="text-xs font-black uppercase tracking-[0.25em] text-electric">Competition table</p><h2 className="mt-2 font-display text-2xl font-black text-white">Standings</h2></div>{standings.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-white/5 text-[10px] font-black uppercase tracking-widest text-white/45"><tr><th className="px-6 py-4">Pos</th><th>Team</th><th className="text-center">P</th><th className="text-center">W</th><th className="text-center">D</th><th className="text-center">L</th><th className="text-center">GD</th><th className="px-6 text-center">PTS</th></tr></thead><tbody>{standings.map((row, index) => <tr key={`${row.team_id}-${index}`} className="border-t border-white/10"><td className="px-6 py-4 font-black text-electric">{index + 1}</td><td className="py-4 font-bold text-white">{row.team_name} <span className="ml-2 text-xs text-white/35">{row.short_code}</span></td>{[row.p, row.w, row.d, row.l, row.gd].map((value, valueIndex) => <td key={valueIndex} className="text-center text-white/60">{value}</td>)}<td className="px-6 text-center font-black text-electric">{row.pts}</td></tr>)}</tbody></table></div> : <p className="p-8 text-center text-white/50">Add teams to see the competition table.</p>}</section>;
}
